# fly.toml app configuration file generated for mj-restore on 2024-11-07T10:25:56-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mj-restore'
primary_region = 'dfw'

[build]
  image = 'micahjj1989/restore:latest'

[env]
  ASPNETCORE_URLS = 'http://+:8080'
  StripeSettings_PublishableKey='pk_test_51QI1l6BpajbHu6WfMyDHz1IRRvoQNPuIVj11p8HUTOKmZwFWZxBBIzMK9PSW2pXSxlmtbkWuaaMUGY4cGPEHURgH00Zq3oGv55'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
